### ISSUE TITLE
No caching for static?

### ISSUE THREAD

**Issue by arrowcircle** [Duet3D/DuetWiFiSocketServer#7]
Hey! It looks like there are no cache headers for static files. DWC is quite heavy JS bundle and esp8255 web server is not nginx. This makes first page load long and it's not good. Does it look like a good idea to add cache headers?

It looks like static files already does have hash in the name, so adding proper cache control headers will solve this problem.

**Comment by dc42** [comment]
Closing this because it belongs in the RepRapFirmware project, not here. We agree with you that adding cache headers would be a good idea and we plan to add them. However, even without them, reloading the first page using control-F5 takes only 2 seconds.
